/// Flutter icons FlutterIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlutterIcon
///      fonts:
///       - asset: fonts/FlutterIcon.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class FlutterIcon {
  FlutterIcon._();

  static const _kFontFam = 'FlutterIcon';

  static const IconData list = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData playlist_add_check =
      const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData th_large_outline =
      const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData baseball =
      const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData cricket = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData rupee = const IconData(0xf156, fontFamily: _kFontFam);
  static const IconData soccer_ball =
      const IconData(0xf1e3, fontFamily: _kFontFam);
}
